// Generated by CoffeeScript 1.3.3
var currentQuestion, generateName, identifier, interpolateQuestion, lastTime, nextTime, publicname, serverTime, socket, stateUpdater, sync_offset, timeFreeze;

socket = io.connect().of(channel_name);

sync_offset = 0;

currentQuestion = null;

lastTime = null;

nextTime = null;

timeFreeze = false;

identifier = Math.random().toString(36).slice(3);

generateName = function() {
  var adjective, animal, pick;
  adjective = 'aberrant,agressive,warty,hoary,breezy,dapper,edgy,feisty,gutsy,hardy,intrepid,jaunty,karmic,lucid,maverick,natty,oneric,precise,quantal';
  animal = 'axolotl,warthog,hedgehog,badger,drake,fawn,gibbon,heron,ibex,jackalope,koala,lynx,meerkat,narwhal,ocelot,penguin,quetzal,kodiak,cheetah,puma,jaguar,panther,tiger,leopard,lion';
  pick = function(list) {
    var n;
    n = list.split(',');
    return n[Math.floor(n.length * Math.random())];
  };
  return pick(adjective) + " " + pick(animal);
};

publicname = generateName();

serverTime = function() {
  if (timeFreeze) {
    return timeFreeze;
  } else {
    return +(new Date) - sync_offset;
  }
};

interpolateQuestion = function(text, time) {
  var index, percent, words;
  percent = (time - lastTime) / (nextTime - lastTime);
  percent = Math.max(0, percent);
  percent = Math.min(1, percent);
  words = text.split(" ");
  index = Math.round(words.length * percent);
  document.querySelector("#visible").innerText = words.slice(0, index).join(' ') + " ";
  return document.querySelector("#unread").innerText = words.slice(index).join(' ');
};

stateUpdater = function() {
  if (currentQuestion) {
    return interpolateQuestion(currentQuestion.question, serverTime());
  }
};

setInterval(stateUpdater, 100);

socket.on('sync', function(data) {
  console.log("sync", data);
  sync_offset = +(new Date) - data.time;
  currentQuestion = data.question;
  lastTime = data.lastTime;
  nextTime = data.nextTime;
  return timeFreeze = data.timeFreeze;
});

socket.on('buzz', function(data) {
  sync_offset = +(new Date) - data.time;
  timeFreeze = data.time;
  return console.log("froze time!");
});

document.addEventListener('keydown', function(e) {
  if (e.keyCode === 13) {
    socket.emit('buzz', {
      name: publicname,
      id: identifier
    });
    return console.log("pressed enter");
  } else if (e.keyCode === 90) {
    return socket.emit('unbuzz', "because the universe makes no sense");
  }
});
