// Generated by CoffeeScript 1.3.3
var answers, checkAnswer, fs, nextQuestion, readline, rl;

fs = require('fs');

readline = require('readline');

rl = readline.createInterface(process.stdin, process.stdout);

checkAnswer = require('./answerparse').checkAnswer;

answers = [];

fs.readFile('sample.txt', 'utf8', function(err, data) {
  var answer, line;
  if (err) {
    throw err;
  }
  answers = (function() {
    var _i, _len, _ref, _results;
    _ref = data.split("\n");
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      line = _ref[_i];
      _results.push(JSON.parse(line).answer);
    }
    return _results;
  })();
  answers = (function() {
    var _i, _len, _results;
    _results = [];
    for (_i = 0, _len = answers.length; _i < _len; _i++) {
      answer = answers[_i];
      if (answer.length < 250) {
        _results.push(answer);
      }
    }
    return _results;
  })();
  answers = answers.sort(function() {
    return Math.random() - 0.5;
  });
  return nextQuestion();
});

nextQuestion = function() {
  var answer;
  answer = answers.shift();
  return rl.question(answer, function(resp) {
    var answ, opt, _i, _len, _ref;
    _ref = resp.split(',');
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      opt = _ref[_i];
      answ = checkAnswer(opt, answer);
      console.log(answ, answ < 1);
      console.log("--------------------");
    }
    return nextQuestion();
  });
};
