// Generated by CoffeeScript 1.3.3

(function() {
  var syllables;
  syllables = function(word) {
    var add, addSyllables, count, fix, part, prefixSuffix, problemWords, sub, subSyllables, tmp, _i, _j, _k, _l, _len, _len1, _len2, _len3, _ref;
    word = word.toLowerCase().replace(/[^a-z]/g, '');
    problemWords = {
      simile: 3,
      forever: 3,
      shoreline: 2
    };
    if (word in problemWords) {
      return problemWords[word];
    }
    prefixSuffix = [/^un/, /^fore/, /ly$/, /less$/, /ful$/, /ers?$/, /ings?$/];
    count = 0;
    for (_i = 0, _len = prefixSuffix.length; _i < _len; _i++) {
      fix = prefixSuffix[_i];
      tmp = word.replace(fix, '');
      if (tmp !== word) {
        count++;
      }
      word = tmp;
    }
    subSyllables = [/cial/, /tia/, /cius/, /cious/, /giu/, /ion/, /iou/, /sia$/, /[^aeiuoyt]{2,}ed$/, /.ely$/, /[cg]h?e[rsd]?$/, /rved?$/, /[aeiouy][dt]es?$/, /[aeiouy][^aeiouydt]e[rsd]?$/, /^[dr]e[aeiou][^aeiou]+$/, /[aeiouy]rse$/];
    addSyllables = [/ia/, /riet/, /dien/, /iu/, /io/, /ii/, /[aeiouym]bl$/, /[aeiou]{3}/, /^mc/, /ism$/, /([^aeiouy])\1l$/, /[^l]lien/, /^coa[dglx]./, /[^gq]ua[^auieo]/, /dnt$/, /uity$/, /ie(r|st)$/];
    _ref = word.split(/[^aeiouy]+/);
    for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
      part = _ref[_j];
      if (part !== '') {
        count++;
      }
    }
    for (_k = 0, _len2 = subSyllables.length; _k < _len2; _k++) {
      sub = subSyllables[_k];
      count -= word.split(sub).length - 1;
    }
    for (_l = 0, _len3 = addSyllables.length; _l < _len3; _l++) {
      add = addSyllables[_l];
      count += word.split(add).length - 1;
    }
    return Math.max(1, count);
  };
  return exports.syllables = syllables;
})();
