//file: client/jade/settings.jade

var settings = function anonymous(locals, attrs, escape, rethrow, merge) {
attrs = attrs || jade.attrs; escape = escape || jade.escape; rethrow = rethrow || jade.rethrow; merge = merge || jade.merge;
var __jade = [{ lineno: 1, filename: "client/jade/settings.jade" }];
try {
var buf = [];
with (locals || {}) {
var interp;
__jade.unshift({ lineno: 1, filename: __jade[0].filename });
__jade.unshift({ lineno: 1, filename: __jade[0].filename });
buf.push('<div class="span3 thumbnail">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 3, filename: __jade[0].filename });
buf.push('<h5>');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 3, filename: __jade[0].filename });
buf.push('<i class="icon-wrench">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.shift();
buf.push('</i>');
__jade.shift();
__jade.unshift({ lineno: 4, filename: __jade[0].filename });
buf.push('Settings');
__jade.shift();
__jade.shift();
buf.push('</h5>');
__jade.shift();
__jade.unshift({ lineno: 6, filename: __jade[0].filename });
buf.push('<div style="text-align: center; padding-right: 4px; padding-left: 4px; padding-top: 4px">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 6, filename: __jade[0].filename });
buf.push('<div class="localsettings">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 7, filename: __jade[0].filename });
buf.push('<div class="expando">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 8, filename: __jade[0].filename });
buf.push('<div class="input-prepend">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 9, filename: __jade[0].filename });
buf.push('<span style="width:21px" title="Public name" rel="tooltip" class="generate-name add-on">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 10, filename: __jade[0].filename });
buf.push('<i class="icon-user">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.shift();
buf.push('</i>');
__jade.shift();
__jade.shift();
buf.push('</span>');
__jade.shift();
__jade.unshift({ lineno: 11, filename: __jade[0].filename });
buf.push('<input id="username" type="text" value="" disabled="disabled"/>');
__jade.shift();
__jade.shift();
buf.push('</div>');
__jade.shift();
__jade.shift();
buf.push('</div>');
__jade.shift();
__jade.unshift({ lineno: 12, filename: __jade[0].filename });
buf.push('<div style="display:none" class="expando set-team">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 13, filename: __jade[0].filename });
buf.push('<div class="input-prepend">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 14, filename: __jade[0].filename });
buf.push('<span style="width:21px" title="Teams" rel="tooltip" class="add-on">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 15, filename: __jade[0].filename });
buf.push('<i class="icon-group">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.shift();
buf.push('</i>');
__jade.shift();
__jade.shift();
buf.push('</span>');
__jade.shift();
__jade.unshift({ lineno: 16, filename: __jade[0].filename });
buf.push('<select class="input teams">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 17, filename: __jade[0].filename });
buf.push('<option value="">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 17, filename: __jade[0].filename });
buf.push('Individual');
__jade.shift();
__jade.shift();
buf.push('</option>');
__jade.shift();
__jade.shift();
buf.push('</select>');
__jade.shift();
__jade.shift();
buf.push('</div>');
__jade.shift();
__jade.shift();
buf.push('</div>');
__jade.shift();
__jade.unshift({ lineno: 18, filename: __jade[0].filename });
buf.push('<div style="display:none" class="expando reset-score">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 19, filename: __jade[0].filename });
buf.push('<div class="input-prepend">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 20, filename: __jade[0].filename });
buf.push('<span style="width:21px" title="Reset my score" rel="tooltip" class="add-on">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 21, filename: __jade[0].filename });
buf.push('<i class="icon-trash">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.shift();
buf.push('</i>');
__jade.shift();
__jade.shift();
buf.push('</span>');
__jade.shift();
__jade.unshift({ lineno: 22, filename: __jade[0].filename });
buf.push('<button class="btn input score-reset">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 22, filename: __jade[0].filename });
buf.push('Reset My Score ');
__jade.shift();
__jade.shift();
buf.push('</button>');
__jade.shift();
__jade.shift();
buf.push('</div>');
__jade.shift();
__jade.shift();
buf.push('</div>');
__jade.shift();
__jade.unshift({ lineno: 24, filename: __jade[0].filename });
buf.push('<div style="display:none" class="expando relinquish-command">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 25, filename: __jade[0].filename });
buf.push('<div class="input-prepend">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 26, filename: __jade[0].filename });
buf.push('<span style="width:21px" title="Relinquish dominance over this room" rel="tooltip" class="add-on">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 27, filename: __jade[0].filename });
buf.push('<i class="icon-eye-close">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.shift();
buf.push('</i>');
__jade.shift();
__jade.shift();
buf.push('</span>');
__jade.shift();
__jade.unshift({ lineno: 28, filename: __jade[0].filename });
buf.push('<button class="btn input lose-command">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 28, filename: __jade[0].filename });
buf.push('Relinquish Command');
__jade.shift();
__jade.shift();
buf.push('</button>');
__jade.shift();
__jade.shift();
buf.push('</div>');
__jade.shift();
__jade.shift();
buf.push('</div>');
__jade.shift();
__jade.unshift({ lineno: 29, filename: __jade[0].filename });
buf.push('<label class="checkbox">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 30, filename: __jade[0].filename });
buf.push('<input type="checkbox" class="movingwindow"/>');
__jade.shift();
__jade.unshift({ lineno: 31, filename: __jade[0].filename });
buf.push('Points earned in last 20 questions');
__jade.shift();
__jade.shift();
buf.push('</label>');
__jade.shift();
__jade.unshift({ lineno: 33, filename: __jade[0].filename });
buf.push('<label class="checkbox">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 34, filename: __jade[0].filename });
buf.push('<input type="checkbox" class="adhd"/>');
__jade.shift();
__jade.unshift({ lineno: 35, filename: __jade[0].filename });
buf.push('Enable distraction free mode');
__jade.shift();
__jade.shift();
buf.push('</label>');
__jade.shift();
__jade.unshift({ lineno: 36, filename: __jade[0].filename });
buf.push('<div class="microwave">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 37, filename: __jade[0].filename });
buf.push('<label class="checkbox">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 38, filename: __jade[0].filename });
buf.push('<input type="checkbox" checked="checked" class="livechat"/>');
__jade.shift();
__jade.unshift({ lineno: 39, filename: __jade[0].filename });
buf.push('Show chat messages while typing');
__jade.shift();
__jade.shift();
buf.push('</label>');
__jade.shift();
__jade.shift();
buf.push('</div>');
__jade.shift();
__jade.unshift({ lineno: 40, filename: __jade[0].filename });
buf.push('<label class="checkbox">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 41, filename: __jade[0].filename });
buf.push('<input type="checkbox" class="sounds"/>');
__jade.shift();
__jade.unshift({ lineno: 42, filename: __jade[0].filename });
buf.push('Play sound on successful buzz');
__jade.shift();
__jade.shift();
buf.push('</label>');
__jade.shift();
__jade.unshift({ lineno: 43, filename: __jade[0].filename });
buf.push('<div style="display:none;white-space:nowrap;" class="lockvote">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 44, filename: __jade[0].filename });
buf.push('<label class="checkbox">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 45, filename: __jade[0].filename });
buf.push('<input type="checkbox" class="lock"/>');
__jade.shift();
__jade.unshift({ lineno: 46, filename: __jade[0].filename });
buf.push('Lock settings <span class=\'electorate\'>0/1 votes</span>');
__jade.shift();
__jade.unshift({ lineno: 47, filename: __jade[0].filename });
buf.push('<i style="padding-left: 5px" class="icon-unlock status_icon">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.shift();
buf.push('</i>');
__jade.shift();
__jade.shift();
buf.push('</label>');
__jade.shift();
__jade.shift();
buf.push('</div>');
__jade.shift();
__jade.shift();
buf.push('</div>');
__jade.shift();
__jade.unshift({ lineno: 49, filename: __jade[0].filename });
buf.push('<hr/>');
__jade.shift();
__jade.unshift({ lineno: 49, filename: __jade[0].filename });
buf.push('<div class="globalsettings">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 51, filename: __jade[0].filename });
buf.push('<div class="expando">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 52, filename: __jade[0].filename });
buf.push('<div class="input-prepend">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 53, filename: __jade[0].filename });
buf.push('<span style="width:21px" title="Read speed" rel="tooltip" class="add-on">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 54, filename: __jade[0].filename });
buf.push('<i class="icon-step-forward">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.shift();
buf.push('</i>');
__jade.shift();
__jade.shift();
buf.push('</span>');
__jade.shift();
__jade.unshift({ lineno: 55, filename: __jade[0].filename });
buf.push('<input type="range" value="200" min="60" max="600" class="speed"/>');
__jade.shift();
__jade.shift();
buf.push('</div>');
__jade.shift();
__jade.shift();
buf.push('</div>');
__jade.shift();
__jade.unshift({ lineno: 56, filename: __jade[0].filename });
buf.push('<div class="expando">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 57, filename: __jade[0].filename });
buf.push('<div class="input-prepend">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 58, filename: __jade[0].filename });
buf.push('<span style="width:21px" title="Difficulty/Category" rel="tooltip" class="add-on">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 59, filename: __jade[0].filename });
buf.push('<i class="icon-briefcase">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.shift();
buf.push('</i>');
__jade.shift();
__jade.shift();
buf.push('</span>');
__jade.shift();
__jade.unshift({ lineno: 60, filename: __jade[0].filename });
buf.push('<select style="width: 60px; border-right: 0" class="padd-on difficulties">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.shift();
buf.push('</select>');
__jade.shift();
__jade.unshift({ lineno: 61, filename: __jade[0].filename });
buf.push('<select style="border-left: 0" class="input categories">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.shift();
buf.push('</select>');
__jade.shift();
__jade.shift();
buf.push('</div>');
__jade.shift();
__jade.shift();
buf.push('</div>');
__jade.shift();
__jade.unshift({ lineno: 62, filename: __jade[0].filename });
buf.push('<div style="display:none" class="custom-category">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.shift();
buf.push('</div>');
__jade.shift();
__jade.unshift({ lineno: 63, filename: __jade[0].filename });
buf.push('<label class="checkbox">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 64, filename: __jade[0].filename });
buf.push('<input type="checkbox" class="showbonus"/>');
__jade.shift();
__jade.unshift({ lineno: 65, filename: __jade[0].filename });
buf.push('Show bonus questions');
__jade.shift();
__jade.shift();
buf.push('</label>');
__jade.shift();
__jade.unshift({ lineno: 66, filename: __jade[0].filename });
buf.push('<label class="checkbox">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 67, filename: __jade[0].filename });
buf.push('<input type="checkbox" checked="checked" class="multibuzz"/>');
__jade.shift();
__jade.unshift({ lineno: 68, filename: __jade[0].filename });
buf.push('Allow players to buzz multiple times');
__jade.shift();
__jade.shift();
buf.push('</label>');
__jade.shift();
__jade.unshift({ lineno: 69, filename: __jade[0].filename });
buf.push('<label class="checkbox">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 70, filename: __jade[0].filename });
buf.push('<input type="checkbox" checked="checked" class="allowskip"/>');
__jade.shift();
__jade.unshift({ lineno: 71, filename: __jade[0].filename });
buf.push('Allow players to skip questions');
__jade.shift();
__jade.shift();
buf.push('</label>');
__jade.shift();
__jade.unshift({ lineno: 72, filename: __jade[0].filename });
buf.push('<label style="display: none" class="checkbox">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 73, filename: __jade[0].filename });
buf.push('<input type="checkbox" checked="checked" class="allowpause"/>');
__jade.shift();
__jade.unshift({ lineno: 74, filename: __jade[0].filename });
buf.push('Allow players to pause questions');
__jade.shift();
__jade.shift();
buf.push('</label>');
__jade.shift();
__jade.unshift({ lineno: 76, filename: __jade[0].filename });
buf.push('<div class="request-access">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 77, filename: __jade[0].filename });
buf.push('<button class="btn btn-large">');
__jade.unshift({ lineno: undefined, filename: __jade[0].filename });
__jade.unshift({ lineno: 77, filename: __jade[0].filename });
buf.push('<i class="icon-cog"></i>&nbsp; Request Access');
__jade.shift();
__jade.shift();
buf.push('</button>');
__jade.shift();
__jade.shift();
buf.push('</div>');
__jade.shift();
__jade.shift();
buf.push('</div>');
__jade.shift();
__jade.shift();
buf.push('</div>');
__jade.shift();
__jade.shift();
buf.push('</div>');
__jade.shift();
__jade.shift();
}
return buf.join("");
} catch (err) {
  rethrow(err, __jade[0].filename, __jade[0].lineno);
}
}



